@url=http://127.0.0.1:8000

## Listar todos os produtos do catálogo
GET {{url}}/seller/v1/catalogo?_limit=50&_offset=0

###
#Cadastrar um produto no catalogo
@api_catalogo={{url}}/seller/v1/catalogo

POST {{api_catalogo}}

{
  "seller_id": "magalu1",
  "sku": "cadeira1",
  "product_name": "cadeira1"
}

###

###
#Cadastrar um produto no catalogo
@api_catalogo={{url}}/seller/v1/catalogo

POST {{api_catalogo}}

{
  "seller_id": "magalu1",
  "sku": "cadeira2",
  "product_name": "cadeira2"
}

###
#Buca todos os produtos de um seller
GET {{api_catalogo}}/magalu1


###
#Atualiza o noem de um produto
PATCH {{api_catalogo}}/MagAlu1/cadeira1

{
  "product_name": "122253"
}

###
# Remove produto
DELETE {{api_catalogo}}/mAgalu1/cadeira1