services:
  keycloak:
    image: quay.io/keycloak/keycloak:24.0.5
    ports:
      - "8080:8080"
      - "8443:8443"
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://keycloak-db:5432/keycloak
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: password
      KEYCLOAK_IMPORT: /opt/keycloak/data/import/marketplace-realm.json
      KC_HOSTNAME: localhost
      KC_HTTP_ENABLED: "true"
      KC_HEALTH_ENABLED: "true"
      KC_METRICS_ENABLED: "true"
      KC_FEATURES: token-exchange
    volumes:
      - ./devtools/keycloak-config:/opt/keycloak/data/import
    depends_on:
      - keycloak-db
    command: ["start-dev"]
    restart: unless-stopped

  keycloak-db:
    image: postgres:13
    hostname: keycloak-db
    ports:
      - "5432:5432" # Porta para acesso direto ao DB (opcional)
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: password # ATENÇÃO: Altere esta senha para produção!
    #volumes:
    #  - keycloak_postgres_data:/var/lib/postgresql/data
    restart: unless-stopped
  # Sem volumes para testes "locais"
  #volumes:
  #  keycloak_data:
  #  keycloak_postgres_data:
