services:
  # Serviço principal da aplicação
  app:
    build:
      context: ..
      dockerfile: devtools/Dockerfile-test
      args:
        GITHUB_TOKEN: ${GITHUB_TOKEN}
    container_name: catalogo
    ports:
      - "8000:8000"
    volumes:
      - ../app:/app/app
    working_dir: /app
    command: uvicorn app.api_main:app --host 0.0.0.0 --port 8000
    env_file:
      - ../.env
    restart: unless-stopped

  # Serviço do banco mongoDB para testes
  mongodb_tests:
    image: mongo:8.0
    container_name: mongodb-tests
    restart: always
    ports:
      - 27018:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
      MONGO_INITDB_DATABASE: test_db

  # Serviço da IA (Ollama)
  ollama:
    image: ollama/ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama:/root/.ollama
    entrypoint: >
      sh -c "ollama serve & sleep 5 && ollama pull phi3 && wait"

volumes:
  ollama:
